apiVersion: v1
kind: Pod
metadata:
  name: emptydir-example
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "while true; do echo $(date) >> /mnt/data/timestamp; sleep 5; done"]
      volumeMounts:
        - name: emptydir-volume
          mountPath: /mnt/data
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"
        requests:
          cpu: "250m"
          memory: "128Mi"
  volumes:
    - name: emptydir-volume
      emptyDir: {}
