- hosts: localhost
  become: true
  become_method: sudo

  vars:
    http_port: 8080

  tasks:
    - name: print port number
      debug: 
        msg: "port number is {{ http_port }}"
    - name: ensure apache is at the latest version
      apt: name=apache2 state=latest
    - name: ensure apache is running
      service: name=apache2 state=started enabled=yes
    - name: copy config
      copy:
        src: foo.conf
        dest: /etc/foo.cof
      notify:
      - restart apache
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted