version: '3.8'

services:
  nginx:
    build:
      context: ./nginx_alb
    container_name: nginx_alb
    ports:
      - "80:80"
    volumes:
      - ./nginx_alb/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - pyfla_app1
      - pyfla_app2
      - pyfla_app3

  pyfla_app1:
    build:
      context: ./pyfla_app1
    container_name: pyfla_app1
    environment:
      - FLASK_ENV=development
    expose:
      - "5000"

  pyfla_app2:
    build:
      context: ./pyfla_app2
    container_name: pyfla_app2
    environment:
      - FLASK_ENV=development
    expose:
      - "5000"

  pyfla_app3:
    build:
      context: ./pyfla_app3
    container_name: pyfla_app3
    environment:
      - FLASK_ENV=development
    expose:
      - "5000"

networks:
  default:
    driver: bridge
